### PR TITLE
[WIP] feat: html via tex4ht, tweaked

### PR DESCRIPTION
**Pull request by pkra**
## Build notes

* https://github.com/michal-h21/dvisvgm4ht
*  `$ make4ht -f html5+dvisvgm_hashes ../notes.tex "mathjax,svg, NoFonts" -c make4ht.cfg`

## First draft issues

* [x] equation ref => manually fixed (added tag, wrapped in math mode)
* [x] added macros to HTML manually => through make4ht
* [x] added css for body max-width
* [x] removed odd MathJax config and changed to SVG
* [x] hand fixed SVGs (only partially) - now dvisvgm based - yay!

## Notes on make4ht

* [x] random tspan (smallcaps) - disable font processing via NoFonts
* [x] 1 png - now svg via dvisvgm
* [ ] title is h2, no main, no landmarks 
* [ ] anchors with just id -- need rewriting, e.g., `$$('a[id]:not([href])').forEach(node => node.parentNode.setAttribute('id', node.getAttribute('id')) && node.remove())`
* [ ] TOC is span soup with nbsps (instead of nav with nested lists) - maybe just drop and do in post-processing?
* [ ] theorem need styling; all have the same class
* [ ] img alt is bad (diagrams)
* [ ] qed just floats right => needs fixng 

## other todo's

* [x] \intertext - maybe \rlap{\text{...}} is ok? 
  *  Yes but better:  define \intertext as a a mathjax macro using rlap and closing the rows
* [x] macros via mathjax configuration
* [x] work out how to add extra styles properly

### CODE REVIEW

**Comment by pkra** [comment]
Overall pretty straight forward

**Comment by pkra** [comment]
Pushed latest version - working SVGs now.

**Comment by pkra** [comment]
Fun bug found: https://github.com/mathjax/MathJax/issues/2624

**Comment by pkra** [comment]
Oooh. nofont is NoFonts...

**Comment by pkra** [comment]
Some nice tips from the developer of make4ht at https://github.com/michal-h21/make4ht/issues/42

**Comment by pkra** [comment]
I'll need to remember https://www.kodymirus.cz/tex4ht-doc/Introduction.html ...

**Comment by pkra** [comment]
Time for a make4ht configuration...

**Comment by michal-h21** [comment]
I see this in the ToDo list:

- random tspan (smallcaps) - disable font processing?

`tspan` elements can be introduced by TikZ. I don't know if you use it in this project (I just saw that you linked it from the `make4ht` issue), but if yes, then it is likely caused by that. You can use the [alternative TikZ driver](https://github.com/michal-h21/dvisvgm4ht), it shouldn't suffer from this issue and it has better support of formatting inside TikZ text nodes.

**Comment by pkra** [comment]
Thanks @michal-h21.  

>     random tspan (smallcaps) - disable font processing?

This was actually in theorem heads. Here's an example from the first commit: https://github.com/scoskey/m522/blob/d938a271c53c590985398076e9359841ac9068f6/html/notes.html#L593.

> You can use the alternative TikZ driver

Thanks, I did switch to that driver (or rather: finally got it to work). It's soooo much better - utf8 encoding, no random closing p tags, no g's inside text / around tspan elements. And so much easier than moving things to standalone.

**Comment by michal-h21** [comment]
> Thanks, I did switch to that driver (or rather: finally got it to work). It's soooo much better - utf8 encoding, no random closing p tags, no g's inside text / around tspan elements. And so much easier than moving things to standalone.

Another way is also TikZ externalization, but it is slower and requires more configurations. This is much easier and in most cases better solution.

**Comment by pkra** [comment]
@scoskey take another look when you get the chance. Should now workly smoothly. Two commits touch the TeX source - one to fix the whitespace, one to wrap the eqref. The rest is now in the config :tada:

**Comment by pkra** [comment]
@scoskey closing this but let's chat about it next time.

**Pull request closed without merging**
